#!/bin/bash

VIM_CMD=""

if [ -z $1 ];then
    VIM_CMD="cd /host/$(pwd) && vim"
else
    VIM_CMD="vim /host/$(realpath $1)"
fi

docker run -it --rm \
    -e COLUMNS=$(tput cols)\
    -e LINES=$(tput lines)\
    -v /:/host \
    vim_env:latest \
    bash -c "$VIM_CMD"



