#!/bin/bash

install_packages() {
    local packages="$@"
    local PREFIX=''	
    if [ $(id -u) -ne 0 ]; then
        # 如果当前用户不是管理员，则使用 sudo 命令执行安装操作
	# 使用-E传递noninteractive参数,环境变量不对sudo生效
	PREFIX='sudo -E DEBIAN_FRONTEND=noninteractive'
    fi

    # 检查软件包是否已经安装
    for pkg in $packages; do
        if ! dpkg-query -W -f='${Status}' $pkg 2>/dev/null | grep -q "^install"; then
            $PREFIX apt-get install -q -y --no-install-recommends --fix-missing $packages
        fi
    done
}

sudo apt-get update
#安装依赖
install_packages ninja-build gettext cmake build-essential unzip curl git

git clone https://github.com/neovim/neovim
cd neovim  && git checkout stable && make CMAKE_BUILD_TYPE=RelWithDebInfo 
cd build && cpack -G DEB && sudo dpkg -i nvim-linux64.deb

#使用nvim替换vim和vi作为默认编辑器，如git commit的输入调用会调用nvim
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --config vi
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
sudo update-alternatives --config vim
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
sudo update-alternatives --config editor


