#!/bin/bash

install_packages() {
    local packages="$@"
    local PREFIX=''	
    if [ $(id -u) -ne 0 ]; then
        # 如果当前用户不是管理员，则使用 sudo 命令执行安装操作
	# 使用-E传递noninteractive参数,环境变量不对sudo生效
	PREFIX='sudo -E DEBIAN_FRONTEND=noninteractive'
    fi

    # 检查软件包是否已经安装
    for pkg in $packages; do
        if ! dpkg-query -W -f='${Status}' $pkg 2>/dev/null | grep -q "^install"; then
            $PREFIX apt-get install -q -y --no-install-recommends --fix-missing $packages
        fi
    done
}

#安装apt组件，用以加ppa
install_packages software-properties-common

#加载ppa
sudo add-apt-repository -y ppa:neovim-ppa/stable
sudo apt-get update

#tzdata需单独的安装才可以避免交互,通过被依赖来安装，仍会出现交互操作
install_packages tzdata

#使用nvim的python功能，使得python脚本可以调用nvim
install_packages python-dev python-pip python3-dev python3-pip python3-neovim 

install_packages neovim

#使用nvim替换vim和vi作为默认编辑器，如git commit的输入调用会调用nvim
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --config vi
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
sudo update-alternatives --config vim
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
sudo update-alternatives --config editor


