#!/bin/bash

docker run -it --rm \
    --user ${USER} \
    -e COLUMNS=$(tput cols)\
    -e LINES=$(tput lines)\
    -v /:/host \
    -w /host/$(pwd) \
    nvim_base:latest \
    bash -c "./install_nvim"




