#!/bin/bash

docker run -it \
    --name nvim_env \
    --user ${USER} \
    --net=host \
    -e DISPLAY=$DISPLAY \
    -v $HOME/.Xauthority:/root/.Xauthority \
    -e COLUMNS=$(tput cols)\
    -e LINES=$(tput lines)\
    -v /:/host \
    -w /host/$(pwd) \
    nvim_test:latest 




